version: '3'
services:
  mlmd-server:
    image: quay.io/mmortari/ml_metadata_store_server:latest
    platform: linux/amd64
    container_name: mlmd-server
    depends_on:
      pgserver:
        condition: service_healthy
    ports:
      - "9090:8080"
    environment:
      - METADATA_STORE_SERVER_CONFIG_FILE=/tmp/shared/conn_config.pb
    volumes:
      - ./test/config/ml-metadata:/tmp/shared
  pgserver:
    image: "postgres:12"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypsw
      PGUSER: postgres
      PGPASSWORD: mypsw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
